
project_id = "asxtdnlznhltawomnguo"

[functions.create-payment]
verify_jwt = false

[functions.create-paypal-payment]
verify_jwt = false

[functions.capture-paypal-payment]
verify_jwt = false

[functions.listing-metrics]
verify_jwt = false
