// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufcvkoqhtyoiqfpgptsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmY3Zrb3FodHlvaXFmcGdwdHN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTgyMzAsImV4cCI6MjA3MDk3NDIzMH0.4LOFo6DwggSPnIA5wDONccIam2_nvz-PqZlTnfEditA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});